# Generated by Django 2.2.13 on 2020-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount_of_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
